/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Registro;
import java.awt.Color;
import java.util.ArrayList;
import modelo.Encomienda;

/**
 *
 * @author JAVIER
 */
public class ListadeEncomiendas extends javax.swing.JFrame {
    public static ListadeEncomiendas instancia;
    /**
     * Creates new form ListadeEncomiendas
     */
    public ListadeEncomiendas() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }
    
    public static ListadeEncomiendas getInstancia(){
        if(instancia == null){
            instancia = new ListadeEncomiendas();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_generarlistados = new javax.swing.JButton();
        tf_id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fondolistado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel2.setText("LISTADO DE ENCOMIENDAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        bt_generarlistados.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        bt_generarlistados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GENERAR VISTA.png"))); // NOI18N
        bt_generarlistados.setText("GENERAR LISTADOS");
        bt_generarlistados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_generarlistadosActionPerformed(evt);
            }
        });
        getContentPane().add(bt_generarlistados, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 20));
        getContentPane().add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 200, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Destinatario", "Direccion", "Tipo", "En domicilio", "Tamaño", "Remitente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1350, 280));

        fondolistado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FONDO PANTALLA FINAL.jpg"))); // NOI18N
        getContentPane().add(fondolistado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //PARSEO SEGURO DE INT
    public static Integer tryParse(String text){
        try {
            return Integer.valueOf(text);
        } catch (NumberFormatException e) {
            return null;
        }
    }
    private void bt_generarlistadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_generarlistadosActionPerformed
        // TODO add your handling code here:
        Integer idBusqueda = tryParse(this.tf_id.getText().trim());
        ArrayList<Encomienda> listaEncontrada = null;
        if(idBusqueda != null){
            listaEncontrada = Registro.buscarListaEncomienda(idBusqueda);
        }
        actualizarTablaEncomiendas(listaEncontrada);
    }//GEN-LAST:event_bt_generarlistadosActionPerformed

    private void actualizarTablaEncomiendas(ArrayList<Encomienda> listaEncontrada){
        ArrayList<Encomienda> lista;
        if(listaEncontrada == null){
            lista = Registro.mostrarEncomiendas();
        }else{
            lista = listaEncontrada;
        }
        String matrix[][] = new String[lista.size()][7];
        for (int i = 0; i < lista.size(); i++) {
            matrix[i][0] = lista.get(i).getId()+"";
            matrix[i][1] = lista.get(i).getDestinatario();
            matrix[i][2] = lista.get(i).getDireccion();
            matrix[i][3] = lista.get(i).getTipo();
            matrix[i][4] = lista.get(i).isEntregaDomicilio()?"Si":"No";
            matrix[i][5] = lista.get(i).getTamano();
            matrix[i][6] = lista.get(i).getRemitente();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                matrix,
                new String[]{
                    "Id","Destinatario","Dirección","Tipo","En Domicilio","Tamaño","Remitente"
                }
        ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadeEncomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadeEncomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadeEncomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadeEncomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadeEncomiendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_generarlistados;
    private javax.swing.JLabel fondolistado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_id;
    // End of variables declaration//GEN-END:variables
}
