/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Registro;
import javax.swing.JOptionPane;
import modelo.Encomienda;

/**
 *
 * @author JAVIER
 */
public class RegistroEncomienda extends javax.swing.JFrame {
    public static RegistroEncomienda instancia;
    /**
     * Creates new form RegistroEncomienda
     */
    public RegistroEncomienda() {
        initComponents();
    }
    
    //SINGLETON DE FORMULARIO
    public static RegistroEncomienda getInstancia(){
        if(instancia == null){
            instancia = new RegistroEncomienda();
        }
        return instancia;
    }
    
    //PARSEO SEGURO DE INT
    public static Integer tryParse(String text){
        try {
            return Integer.valueOf(text);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rb_sobre = new javax.swing.JRadioButton();
        rb_paquetes = new javax.swing.JRadioButton();
        Cb_entregadomicilio = new javax.swing.JCheckBox();
        cb_tamaño = new javax.swing.JComboBox<>();
        bt_Buscar_id = new javax.swing.JButton();
        bt_agregar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_limpiar = new javax.swing.JButton();
        tf_id = new javax.swing.JTextField();
        tf_destinatario = new javax.swing.JTextField();
        tf_direccion = new javax.swing.JTextField();
        tf_remitente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fondoregistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.SystemColor.control);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 37, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel2.setText("REGISTRO DE ENCOMIENDA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Direccion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 162, 80, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Tipo De Encomienda");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 290, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Tamaño");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("Remitente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        buttonGroup1.add(rb_sobre);
        rb_sobre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        rb_sobre.setText("Sobre");
        getContentPane().add(rb_sobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 65, -1));

        buttonGroup1.add(rb_paquetes);
        rb_paquetes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        rb_paquetes.setSelected(true);
        rb_paquetes.setText("Paquete");
        rb_paquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_paquetesActionPerformed(evt);
            }
        });
        getContentPane().add(rb_paquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 90, -1));

        Cb_entregadomicilio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Cb_entregadomicilio.setText("Entrega a domicilio");
        getContentPane().add(Cb_entregadomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 160, -1));

        cb_tamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeña", "Mediana", "Grande" }));
        cb_tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tamañoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 150, -1));

        bt_Buscar_id.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_Buscar_id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buska.png"))); // NOI18N
        bt_Buscar_id.setText("Buscar ID");
        bt_Buscar_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Buscar_idActionPerformed(evt);
            }
        });
        getContentPane().add(bt_Buscar_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        bt_agregar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga.jpg"))); // NOI18N
        bt_agregar.setText("   Agregar");
        bt_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 150, 40));

        bt_modificar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mod.png"))); // NOI18N
        bt_modificar.setText("   Modificar");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 150, 40));

        bt_limpiar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.jpg"))); // NOI18N
        bt_limpiar.setText("   Limpiar");
        bt_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 150, 40));

        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });
        getContentPane().add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 148, -1));

        tf_destinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_destinatarioActionPerformed(evt);
            }
        });
        getContentPane().add(tf_destinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 119, 300, -1));
        getContentPane().add(tf_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 300, -1));
        getContentPane().add(tf_remitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 300, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DELIVERYEXPRESS (1).jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 110, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIPO ENCOMIENDA2.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setText("Destinatario");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 122, -1, -1));

        fondoregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FONDO FINAL SEGUNDA PANTALLA.jpg"))); // NOI18N
        getContentPane().add(fondoregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 800, 540));

        getAccessibleContext().setAccessibleName("Registro Encomienda");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_paquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_paquetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_paquetesActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void bt_Buscar_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Buscar_idActionPerformed
        // TODO add your handling code here:
        Integer idBusqueda = tryParse(this.tf_id.getText().trim())  ;
        if(idBusqueda == null){
            JOptionPane.showMessageDialog(rootPane,"No se ha ingresado un Id de Encomienda");
        }else{
            this.tf_id.setEnabled(false);
            Encomienda encontrado = Registro.buscarPorEncomienda(idBusqueda);
            this.tf_destinatario.setText(encontrado.getDestinatario());
            this.tf_direccion.setText(encontrado.getDireccion());
            this.tf_remitente.setText(encontrado.getRemitente());
            this.cb_tamaño.setSelectedItem(encontrado.getTamano());
            if("paquete".equalsIgnoreCase(encontrado.getTipo())){
                this.rb_paquetes.setSelected(true);
            }else{
                this.rb_sobre.setSelected(true);
            }
            this.Cb_entregadomicilio.setSelected(encontrado.isEntregaDomicilio());
            
        }
        
        
    }//GEN-LAST:event_bt_Buscar_idActionPerformed

    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
        // TODO add your handling code here:
        this.tf_id.setEnabled(true);
        this.tf_id.setText("");
        this.tf_destinatario.setText("");
        this.tf_direccion.setText("");
        this.tf_remitente.setText("");
        this.cb_tamaño.setSelectedIndex(0);
        this.rb_paquetes.setSelected(true);
        this.Cb_entregadomicilio.setSelected(false);
    }//GEN-LAST:event_bt_limpiarActionPerformed

    private void tf_destinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_destinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_destinatarioActionPerformed

    private void cb_tamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tamañoActionPerformed

    private void bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarActionPerformed
        // TODO add your handling code here:
        try {
            
            String validationMsg = "";
            Encomienda enc = new Encomienda();
            enc.setId(tryParse(this.tf_id.getText()));
            enc.setDestinatario(this.tf_destinatario.getText().trim());
            enc.setDireccion(this.tf_direccion.getText().trim());
            enc.setRemitente(this.tf_remitente.getText().trim());
            enc.setTamano(this.cb_tamaño.getSelectedItem().toString().trim());
            enc.setTipo(this.rb_paquetes.isSelected()?"paquete":"sobre");
            enc.setEntregaDomicilio( this.Cb_entregadomicilio.isSelected());
            validationMsg = Encomienda.validarEncomienda(enc);
          
            if(!"".equals(validationMsg)){
                JOptionPane.showMessageDialog(rootPane, validationMsg);
                return;
            }
          
            boolean saved = Registro.Agregar(enc);
            if(saved){
                JOptionPane.showMessageDialog(this, "Registro de Encomienda Grabado");
            }else{
                JOptionPane.showMessageDialog(this, "NO se registró Encomienda!!!");
            }
            System.out.println(enc.toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }

        
    }//GEN-LAST:event_bt_agregarActionPerformed

    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        // TODO add your handling code here:
        try {
            String validationMsg ="";
            Encomienda encEditada = new Encomienda();
            encEditada.setId(tryParse(this.tf_id.getText()));
            encEditada.setDestinatario(this.tf_destinatario.getText().trim());
            encEditada.setDireccion(this.tf_direccion.getText().trim());
            encEditada.setRemitente(this.tf_remitente.getText().trim());
            encEditada.setTamano(this.cb_tamaño.getSelectedItem().toString().trim());
            encEditada.setTipo(this.rb_paquetes.isSelected()?"paquete":"sobre");
            encEditada.setEntregaDomicilio( this.Cb_entregadomicilio.isSelected());
            validationMsg = Encomienda.validarEncomienda(encEditada);
             if(!"".equals(validationMsg)){
                JOptionPane.showMessageDialog(rootPane, validationMsg);
                return;
            }
          
            boolean saved = Registro.Editar(encEditada);
            if(saved){
                JOptionPane.showMessageDialog(this, "Registro de Encomienda Editado");
            }else{
                JOptionPane.showMessageDialog(this, "NO se editó Encomienda!!!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }//GEN-LAST:event_bt_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEncomienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Cb_entregadomicilio;
    private javax.swing.JButton bt_Buscar_id;
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_limpiar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_tamaño;
    private javax.swing.JLabel fondoregistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rb_paquetes;
    private javax.swing.JRadioButton rb_sobre;
    private javax.swing.JTextField tf_destinatario;
    private javax.swing.JTextField tf_direccion;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_remitente;
    // End of variables declaration//GEN-END:variables
}
